version: 2

models:

    - name: stg_payments
      description: The payments made through Stripe
      columns: 
        - name: payment_id
          description: "{{doc('payment_id')}}"
        - name: order_id
          description: "{{doc('order_id')}}"
        - name: payment_method
          description: "{{doc('payment_method')}}"
        - name: status
          description: "{{doc('status')}}"
        - name: amount
          description: "{{doc('amount')}}"
        - name: created_at
          description: "{{doc('created_at')}}" 